# Generated by Django 4.1.7 on 2023-03-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='purchaed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
