# Generated by Django 4.1.7 on 2023-03-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_employee_designation'),
        ('devices', '0002_devices_purchaed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Printer', max_length=120)),
                ('price', models.IntegerField(default=999)),
                ('purchased_at', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
