# Generated by Django 4.1.7 on 2023-03-13 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_employee_designation'),
        ('devices', '0004_device_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 13, 17, 24, 47, 323758, tzinfo=datetime.timezone.utc), null=True)),
                ('condition_when_checkout', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default='good', max_length=10)),
                ('condition_when_return', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default='good', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.employee')),
            ],
        ),
    ]
