# Generated by Django 4.1.7 on 2023-03-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceshare',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
