# Generated by Django 4.1.7 on 2023-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribute', '0002_alter_deviceshare_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceshare',
            name='condition_when_return',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default='good', max_length=10, null=True),
        ),
    ]
