# Generated by Django 4.1.7 on 2023-03-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_owner_alter_company_establised_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('owner', 'Owner'), ('etc', 'ETC')], max_length=20, null=True),
        ),
    ]
